name: Latest DevDojo blog post workflow
on:
  schedule:
    # Runs every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-dev:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "DEV-POST-LIST"
          feed_list: "https://dev.to/feed/oriiyx"
          commit_message: "Add post from Dev"
          committer_email: "41898282+github-actions[bot]@users.noreply.github.com"